### ISSUE TITLE
Music never triggers. 1.20.1

### ISSUE THREAD

**Issue by StormbringerGTX** [Maki99999/music-by-biome#2]
Wonderful mod but I am unable to get it to work.

I followed the directions and I have a custom set of .ogg music files tied to specific biomes and events.

You can see the list I created here:
https://pastebin.com/ghDPDaMS

I also created the folder structure for the sounds as directed:
https://drive.google.com/file/d/11Uu7YCb-mP5YvuMuvTABl-f16v9BxqjK/view?usp=drive_link

The mod loads fine and doesn't throw up any errors but refuses to play any music at all only displaying "playing: minecraft:empty" when debug mod is enabled.

**Comment by Maki99999** [comment]
Duplicate of #9
